IGEPainel = [
  {
    "seq": 17,
    "descricao": "DX1 - ÁCAROS",
    "codigo": "DX1",
    "classe": "ACAROS",
    "secao": "DB APOIO",
    "prazo": 3,
    "ativo": "S",
    "rodape": "Alergenos pesquisados: D1 (Dermatophagoides pteronyssinus), D2 (Dermatophagoides farinae), D3 (Dermatophagoides microceras), D71 (Lepidoglyphus destructor), D72 (Tyrophagus putrescentiae), D73 (Glycyphagus domesticus), D74 (Euroglyphus maynei) e D201 (Blomia tropicalis).",
  },
  {
    "seq": 3,
    "descricao": "EP6 - ALIMENTOS",
    "codigo": "EP6",
    "classe": "ALIMENTOS",
    "secao": "DB APOIO",
    "prazo": 5,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: F4 (Trigo), F9 (Arroz), F10 (Gergelim), F11 (Trigo-sarraceno) e F14 ( Soja).",
   
  },
  {
    "seq": 1,
    "descricao": "EX1 - ANIMAIS",
    "codigo": "EX1",
    "classe": "EPITÉLIOS",
    "secao": "DB APOIO",
    "prazo": 5,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: E1 (Epitélio de gato), E3 (Caspa de cavalo), E4 (Caspa de Boi) e E5 (Caspa de cachorro).",
   
  },
  {
    "seq": 18,
    "descricao": "EX2 - ANIMAIS",
    "codigo": "EX2",
    "classe": "EPITÉLIOS",
    "secao": "DB APOIO",
    "prazo": 5,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: (E1) - Epitélio de gato; (E5) - Epitélio de cachorro; (E6) - Epitélio de coabaia; (E87) - Epitélio de rato e (E88) - Pêlo de camundongo.",
   
  },
  {
    "seq": 19,
    "descricao": "EX70 - ANIMAIS",
    "codigo": "EX70",
    "classe": "EPITÉLIOS",
    "secao": "DB APOIO",
    "prazo": 10,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: E6 (Epitélio de cobaia), E82 (Epitélio de coelho), E84 (Epitélio de hamster), E87 (Epitélio de Rato) e E88 (Epitélio de Camundongo).",
   
  },
  {
    "seq": 11,
    "descricao": "EX71 - PENAS",
    "codigo": "EX71",
    "classe": "PENAS",
    "secao": "DB APOIO",
    "prazo": 5,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: E70 (Pena de ganso), E85 (Pena de galinha), E86 (Pena de pato) e E89 (Pena de peru).",
   
  },
  {
    "seq": 15,
    "descricao": "EX72 - PENAS",
    "codigo": "EX72",
    "classe": "PENAS",
    "secao": "DB APOIO",
    "prazo": 5,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: (E78) - Pena de budigericar (papagaio australiano); (E201) - Pena de canário; (E196) - Pena de periquito; (E213) - Pena de papagaio e (E214) - Pena de tentilhão.",
   
  },
  {
    "seq": 50,
    "descricao": "EX73 - PENAS",
    "codigo": "EX73",
    "classe": "PENAS",
    "secao": "DB APOIO",
    "prazo": 10,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: (E70) - Pena de ganso; (E85) - Pena de galinha; (E86) - Pena de pato e (E213) - Pena de papagaio.",
   
  },
  {
    "seq": 2,
    "descricao": "FX1 - ALIMENTOS",
    "codigo": "FX1",
    "classe": "ALIMENTOS",
    "secao": "DB APOIO",
    "prazo": 5,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: F13 (Amendoim),  F17 (Avelã), F18 (Castanha do Pará),  F20 (Amêndoa)  e  F36 (Coco).",
   
  },
  {
    "seq": 51,
    "descricao": "FX10 - ALIMENTOS",
    "codigo": "FX10",
    "classe": "ALIMENOS",
    "secao": "DB APOIO",
    "prazo": 12,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: F26 - Carne de porco; F27 - Carne de vaca; F75 - Gema de ovo; F83 - Carne de galinha e F284 - Carne de peru.",
   
  },
  {
    "seq": 20,
    "descricao": "FX13 - ALIMENTOS",
    "codigo": "FX13",
    "classe": "ALIMENTOS",
    "secao": "DB APOIO",
    "prazo": 10,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: F12 (Ervilha), F15 (Feijão branco), F31 (Cenoura) e F35 (Batata).",
   
  },
  {
    "seq": 21,
    "descricao": "FX15 - ALIMENTOS",
    "codigo": "FX15",
    "classe": "ALIMENTOS",
    "secao": "DB APOIO",
    "prazo": 5,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: F33 (Laranja), F49 (Maçã), F92 (Banana) e F95 (Pêssego).",
   
  },
  {
    "seq": 22,
    "descricao": "FX16 - ALIMENTOS",
    "codigo": "FX16",
    "classe": "ALIMENTOS",
    "secao": "DB APOIO",
    "prazo": 10,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: F44 (Morango), F94 (Pêra), F208 (Limão) e F210 (Ananás).",
   
  },
  {
    "seq": 23,
    "descricao": "FX18 - ALIMENTOS",
    "codigo": "FX18",
    "classe": "ALIMENTOS",
    "secao": "DB APOIO",
    "prazo": 12,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: F12 (Ervilha), (F13) Amendoim e (F14) Grão de soja.",
   
  },
  {
    "seq": 4,
    "descricao": "FX2 - ALIMENTOS",
    "codigo": "FX2",
    "classe": "ALIMENTOS",
    "secao": "DB APOIO",
    "prazo": 5,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: F3 (Bacalhau/peixe), F24 (Camarão), F37 (Mexilhão Azul), F40 (Atum) e F41 (Salmão).",
   
  },
  {
    "seq": 24,
    "descricao": "FX20 - ALIMENTOS",
    "codigo": "FX20",
    "classe": "ALIMENTOS",
    "secao": "DB APOIO",
    "prazo": 12,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: F4 (Trigo), F5 (Centeio), F6 (Cevada) e F9 (Arroz).",
   
  },
  {
    "seq": 52,
    "descricao": "FX25 - ALIMENTOS",
    "codigo": "FX25",
    "classe": "ALIMENTOS",
    "secao": "DB APOIO",
    "prazo": 10,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: (F10) - Gergelim; (F45) - Levedura; (F47) - Alho e (F85) - Aipo.",
   
  },
  {
    "seq": 5,
    "descricao": "FX3 - ALIMENTOS",
    "codigo": "FX3",
    "classe": "ALIMENTOS",
    "secao": "DB APOIO",
    "prazo": 5,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: F4 (Trigo), F7 (Aveia), F8 (Milho), F10 (Gergelim/Sézamo) e F11 (Trigo-sarraceno).",
   
  },
  {
    "seq": 6,
    "descricao": "FX5 - ALIMENTOS",
    "codigo": "FX5",
    "classe": "ALIMENTOS",
    "secao": "DB APOIO",
    "prazo": 5,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: F1 (Clara de ovo), F2 (Leite), F3 (Bacalhau/peixe), F4 (Trigo), F13 (Amendoim) e F14 (Soja).",
   
  },
  {
    "seq": 53,
    "descricao": "FX6 - ALIMENTOS",
    "codigo": "FX6",
    "classe": "ALIMENTOS",
    "secao": "DB APOIO",
    "prazo": 5,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: (F4) - Trigo; (F9) - Arroz; (F10) - Gergelin; (F11) - Trigo serraceno e (F14) - Soja.",
   
  },
  {
    "seq": 14,
    "descricao": "FX7 - ALIMENTOS",
    "codigo": "FX7",
    "classe": "ALIMENTOS",
    "secao": "DB APOIO",
    "prazo": 5,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: F1 (Clara de ovo), F2 (Leite de vaca), F4 (Trigo), F9 (Arroz), F13 (Amendoim) e F14 (Soja).",
   
  },
  {
    "seq": 54,
    "descricao": "FX72 - ALIMENTOS",
    "codigo": "FX72",
    "classe": "ALIMENTOS",
    "secao": "DB APOIO",
    "prazo": 12,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: F269 - Menjericão; W46 - Funcho; F276 - Erva doce; F270 - Gengibre e F271 - Anis.",
   
  },
  {
    "seq": 25,
    "descricao": "FX73 - ALIMENTOS",
    "codigo": "FX73",
    "classe": "ALIMENTOS",
    "secao": "DB APOIO",
    "prazo": 10,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: F26 (Carne de porco), F27 (Carne de boi), F83 (Carne de frango) e F88 (Carne de cordeiro).",
   
  },
  {
    "seq": 26,
    "descricao": "FX74 - ALIMENTOS",
    "codigo": "FX74",
    "classe": "ALIMENTOS",
    "secao": "DB APOIO",
    "prazo": 12,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: F3 (Peixe/bacalhau), F50 (Cavala/sarda), F205 (Arenque) e F254 (Solha).",
   
  },
  {
    "seq": 7,
    "descricao": "FX8 - ALIMENTOS",
    "codigo": "FX8",
    "classe": "ALIMENTOS",
    "secao": "DB APOIO",
    "prazo": 10,
    "ativo": "S",
    "rodape": "Alérgenos Pesquisados: F17 (Avelã), F18 (Castanha do Pará), F33 (Laranja), F49 (Maçã) e F93 (Cacau).",
   
  },
  {
    "seq": 27,
    "descricao": "FX9 - ALIMENTOS",
    "codigo": "FX9",
    "classe": "ALIMENTOS",
    "secao": "DB APOIO",
    "prazo": 10,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: F20 (Amêndoa), F84 (Kiwi), F87 (Melão), F92 (Banana) e F259 (Uva).",
   
  },
  {
    "seq": 29,
    "descricao": "GX1 - GRAMÍNEAS",
    "codigo": "GX1",
    "classe": "GRAMÍNEAS",
    "secao": "DB APOIO",
    "prazo": 5,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: Pólen de gramíneas: (G3) - Grama de pomar; (G4) - Prado; (G5) - Centeio perene; (G8) - Capim de junho e (G6) - Capim timóteo.",
   
  },
  {
    "seq": 8,
    "descricao": "GX2 - GRAMÍNEAS",
    "codigo": "GX2",
    "classe": "GRAMÍNEAS",
    "secao": "DB APOIO",
    "prazo": 5,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: Pólen de gramíneas: G2 (Grama das Bermudas), G5 (Centeio Perene), G6 (Grama tipo Timóteo), G8 (Grama de Junho), G10 (Grama tipo Johnson) e G17 (Grama tipo Bahia).",
   
  },
  {
    "seq": 30,
    "descricao": "GX3 - GRAMÍNEAS",
    "codigo": "GX3",
    "classe": "GRAMÍNEAS",
    "secao": "DB APOIO",
    "prazo": 5,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: Pólen de Gramíneas: (G1) - Grama de cheiro; (G5) - Centeio perene; (G6) - Grama timóteo; (G12) - Centeio cultivado e (G13) - Grama veludo.",
   
  },
  {
    "seq": 31,
    "descricao": "GX4 - GRAMINEAS",
    "codigo": "GX4",
    "classe": "GRAMÍNEAS",
    "secao": "DB APOIO",
    "prazo": 12,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: Pólen de gramíneas: (G1) Cheiro de feno; (G5) Azevém; (G7) Caniço; (G12) Centeio e (G13) Erva lanar.",
   
  },
  {
    "seq": 28,
    "descricao": "GX6 - GRAMÍNEAS",
    "codigo": "GX6",
    "classe": "GRAMÍNEAS",
    "secao": "DB APOIO",
    "prazo": 5,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: Pólen de gramíneas: (G1) - Grama de cheiro; (G5) - Centeio perene; (G10) - Grama tipo johnson; (G11) - Capim cevadinha; (G13) - Centeio cultivado e (G17) - Grama tipo bahia.",
   
  },
  {
    "seq": 49,
    "descricao": "HX1 - POEIRA DOMÉSTICA",
    "codigo": "HX1",
    "classe": "INALANTES",
    "secao": "DB APOIO",
    "prazo": 5,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: (H1) - Poeira caseira - Greer lab, (D1) - Ácaros - D. pteronyssinus, (D2) - Ácaros - D. farinae e (I6) - Insetos - Barata",
   
  },
  {
    "seq": 9,
    "descricao": "HX2 - POEIRA DOMÉSTICA",
    "codigo": "HX2",
    "classe": "INALANTES",
    "secao": "DB APOIO",
    "prazo": 5,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: H1 (Poeira caseira - Hollister stier lab),  D1 (Dermatophagoides pteronissinus),  D2 (Dermatophagoides farinae ) e I6 (Blatella germanica, barata).",
   
  },
  {
    "seq": 55,
    "descricao": "IX1 - INALANTES",
    "codigo": "IX1",
    "classe": "INALANTES",
    "secao": "DB APOIO",
    "prazo": 10,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: (G2) Grama Mayor; (G5) Ballico; (G6) Hierba Timotea; (G8) Espiguilla; (G10) Millaca e (G17 ) Panizo de las pampas.",
   
  },
  {
    "seq": 12,
    "descricao": "IX6 - INALANTES",
    "codigo": "IX6",
    "classe": "INALANTES",
    "secao": "DB APOIO",
    "prazo": 5,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: G6 (Grama tipo timóteo), M2 (Cladosporium herbarum), M6 (Alternaria alternata/tenuis), T3 (Vidoeiro) e W6 (Artemísia).",
   
  },
  {
    "seq": 32,
    "descricao": "KX1 - OCUPACIONAIS",
    "codigo": "KX1",
    "classe": "OCUPACIONAIS",
    "secao": "DB APOIO",
    "prazo": 5,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: E3 (Caspa de Cavalo), E4 (Caspa de Boi), E70 (Pena de Ganso) e E85 (Pena de Galinha).",
   
  },
  {
    "seq": 10,
    "descricao": "MX1 - FUNGOS",
    "codigo": "MX1",
    "classe": "FUNGOS",
    "secao": "DB APOIO",
    "prazo": 5,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: M1 (Penicillium notatum), M2 (Cladosporium herbarum), M3 (Aspergillus fumigatus)  e M6 (Alternaria alternata/tenuis).",
   
  },
  {
    "seq": 13,
    "descricao": "MX2 - FUNGOS",
    "codigo": "MX2",
    "classe": "FUNGOS",
    "secao": "DB APOIO",
    "prazo": 5,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: M1 (Penicillium notatum), M2 (Cladosporium herbarum), M3 (Aspergillus fumigatus), M5 (Candida albicans) e M6 (Alternaria alternata).",
   
  },
  {
    "seq": 48,
    "descricao": "PAX4 - ALIMENTOS",
    "codigo": "PAX4",
    "classe": "ALIMENTOS",
    "secao": "DB APOIO",
    "prazo": 12,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: (W7) - Margarida olho de boi; (W8) - Dente de leão; (W9) - Plântago lanceolata; (W10) - Quenódipo e (W12) - Vara dourada.",
   
  },
  {
    "seq": 33,
    "descricao": "TP7 - ARVORES***",
    "codigo": "TP7",
    "classe": "ARVORES",
    "secao": "DB APOIO",
    "prazo": 5,
    "ativo": "N",
    "rodape": "Alérgenos pesquisados: T9 (Oliveira), T12 (Salgueiro), T16 (Pinheiro branco), T18 (Eucalipto), T19 (Acacia).",
   
  },
  {
    "seq": 35,
    "descricao": "TX1 - ARVORES",
    "codigo": "TX1",
    "classe": "ARVORES",
    "secao": "DB APOIO",
    "prazo": 5,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: T1 (Acerácea), T3 (Vidoeiro), T7 (Carvalho), T8 (Olmeiro) e T10 (Nogueira).",
   
  },
  {
    "seq": 36,
    "descricao": "TX2 - ARVORES",
    "codigo": "TX2",
    "classe": "ARVORES",
    "secao": "DB APOIO",
    "prazo": 5,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: T1 (Acerácea), T7 (Carvalho), T8 (Olmeiro), T14 (Algodoeiro) e T22 (Nogueira-Pecã).",
   
  },
  {
    "seq": 37,
    "descricao": "TX3 - ARVORES",
    "codigo": "TX3",
    "classe": "ARVORES",
    "secao": "DB APOIO",
    "prazo": 5,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: T6 (Cedro da Montanha), T7 (Carvalhos), T8 (Olmeiro), T14 (Algodoeiro) e T20 (Algarobeira).",
   
  },
  {
    "seq": 38,
    "descricao": "TX4 - ARVORES",
    "codigo": "TX4",
    "classe": "ARVORES",
    "secao": "DB APOIO",
    "prazo": 12,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: T7 (Carvalho), T8 (Olmeiro), T11 (Sicômoro), T12 (Salgueiro) e T14 (Algodoeiro).",
   
  },
  {
    "seq": 39,
    "descricao": "TX5 - ARVORES",
    "codigo": "TX5",
    "classe": "ARVORES",
    "secao": "DB APOIO",
    "prazo": 5,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: T2 (Amieiro), T4 (Aveleira), T8 (Olmeiro), T12 (Salgueiro) e T14 (Algodoeiro).",
   
  },
  {
    "seq": 40,
    "descricao": "TX6 - ARVORES",
    "codigo": "TX6",
    "classe": "ARVORES",
    "secao": "DB APOIO",
    "prazo": 12,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: T1 (Acerácea), T3 (Vidoeiro), T5 (Faia), T7 (Carvalho) e T10 (Nogueira).",
   
  },
  {
    "seq": 34,
    "descricao": "TX7 - ARVORES",
    "codigo": "TX7",
    "classe": "ARVORES",
    "secao": "DB APOIO",
    "prazo": 5,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: T9 (Oliveira), T12 (Salgueiro), T16 (Pinheiro Branco), T18 (Eucalipto), T19 (Acácia) e T21 (Melaleuca).",
   
  },
  {
    "seq": 41,
    "descricao": "TX8 - ARVORES",
    "codigo": "TX8",
    "classe": "ARVORES",
    "secao": "DB APOIO",
    "prazo": 10,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: T1 (Acerácea), T3 (Vidoeiro), T4 (Aveleiro), T7 (Carvalho) e T11 (Sicômoro).",
   
  },
  {
    "seq": 42,
    "descricao": "TX9 - ARVORES",
    "codigo": "TX9",
    "classe": "ARVORES",
    "secao": "DB APOIO",
    "prazo": 17,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: T2 (Amieiro), T3 (Vidoeiro), T4 (Aveleiro), T7 (Carvalho) e T12 (Salgueiro).",
   
  },
  {
    "seq": 43,
    "descricao": "WX1 - ERVAS DANINHAS",
    "codigo": "WX1",
    "classe": "ERVAS DANINHAS",
    "secao": "DB APOIO",
    "prazo": 10,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: W1 (Erva daninha comum), W6 (Artemísia), W9 (Plantago lanceolata), W10 (Quenopódio) e W15 (Atriplex lentiformis).",
   
  },
  {
    "seq": 44,
    "descricao": "WX2 - ERVAS DANINHAS",
    "codigo": "WX2",
    "classe": "ERVAS DANINHAS",
    "secao": "DB APOIO",
    "prazo": 10,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: W2 (Erva daninha do oeste), W6 (Artemísia), W9 (Plantago lanceolata), W10 (Quenopódio) e W15 (Atriplex lentiformis).",
   
  },
  {
    "seq": 45,
    "descricao": "WX3 - ERVAS DANINHAS",
    "codigo": "WX3",
    "classe": "ERVAS DANINHAS",
    "secao": "DB APOIO",
    "prazo": 10,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: W6 (Artemísia), W9 (Plantago lanceolata), W10 (Quenopódio), W12 (Vara Dourada) e W20 (Urtiga).",
   
  },
  {
    "seq": 46,
    "descricao": "WX5 - ERVAS DANINHAS",
    "codigo": "WX5",
    "classe": "ERVAS DANINHAS",
    "secao": "DB APOIO",
    "prazo": 5,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: W1 (Erva daninha comum), W6 (Artemísia), W7 (Margarida olho de boi), W8 (Dente de leão) e W12 (Vara dourada).",
   
  },
  {
    "seq": 47,
    "descricao": "WX6 - ERVAS DANINHAS",
    "codigo": "WX6",
    "classe": "ERVAS DANINHAS",
    "secao": "DB APOIO",
    "prazo": 10,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: W9 (Plantago lanceolata), W10 (Quenopódio), W11 (Salsola pestifer) e W18 (Azedinha).",
   
  },
  {
    "seq": 16,
    "descricao": "WX7 - ERVAS DANINHAS",
    "codigo": "WX7",
    "classe": "ERVAS DANINHAS",
    "secao": "DB APOIO",
    "prazo": 5,
    "ativo": "S",
    "rodape": "Alérgenos pesquisados: W7 (Margarida olho de boi), W8 (Dente de leão), W9 (Plantago lanceolata), W10 (Quenopódio) e W12 (Vara dourada).",
   
  }
]